#!/bin/sh
# Manage dsh deployment users: create | reset-password | remove | list.
#
# One authenticated user spans three configuration files that must stay in sync
# (see README「用户管理」):
#   authelia/users_database.yml   argon2id credentials + groups (must contain
#                                 "dsh": configuration.yml's ACL rule grants by
#                                 "group:dsh"; group membership hot-reloads via
#                                 authentication_backend.file.watch, so create/
#                                 remove never touches configuration.yml)
#   compose.yaml                  dsh-<name> runtime instance; declaration order
#                                 is contractual: the first service is the
#                                 no-auth single instance (primary)
#   nginx/gateway/default.conf.template   upstream dsh_<name> + $dsh_user routing map
#
# Inputs arrive via the environment (set by the Taskfile tasks; exporting them
# by hand works too):
#   DSH_USER_ARGS      raw positional arguments "<name> <password>"
#   DSH_USER_NAME      explicit name (task user:create NAME=..) — takes precedence
#   DSH_USER_PASSWORD  explicit password (task user:create PASSWORD=..); unlike
#                      the positional form this may contain whitespace
#   DSH_DOMAIN         email domain for new users (default harness.deepseek.com)
#
# Password digests are generated by the authelia image itself (authelia
# crypto hash generate argon2). Every input is validated and the digest generated BEFORE the
# first file is touched; edits rewrite through temp-file + mv (the users
# database is appended at EOF) so a failure never leaves a half-edited file
# behind. remove never deletes dsh-home/<name> or workspace/<name>.

set -u

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit 2
ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd) || exit 2

USERS_DB="$ROOT/authelia/users_database.yml"
AUTH_CONF="$ROOT/authelia/configuration.yml"
COMPOSE_FILE="$ROOT/compose.yaml"
GATEWAY_CONF="$ROOT/nginx/gateway/default.conf.template"
MODE_HELPER="$SCRIPT_DIR/compose_mode.sh"

die() {
  echo "error: $*" >&2
  exit 2
}

usage() {
  cat >&2 <<'EOF'
usage:
  task user:create -- <name> <password>
      (or: task user:create NAME=<name> PASSWORD=<password> for whitespace passwords)
  task user:reset_password -- <name> <password>
  task user:remove -- <name>
  task user:list
EOF
}

# ---------------------------------------------------------------------------
# Input handling
# ---------------------------------------------------------------------------
ARG_COUNT=0
ARG_1=
ARG_2=

# Word-split DSH_USER_ARGS into positional parameters (globbing disabled;
# default IFS also collapses runs of spaces/tabs).
split_args() {
  set -f
  set -- ${DSH_USER_ARGS-}
  ARG_COUNT=$#
  ARG_1=${1-}
  ARG_2=${2-}
  set +f
}

# A user name must yield a safe compose service (dsh-<name>), container name
# (dsh-web-<name>), YAML key, and nginx map key.
RESERVED_NAMES='runtime single http auth-http'

validate_name() {
  _name=$1
  for _r in $RESERVED_NAMES; do
    [ "$_name" = "$_r" ] \
      && die "user name '$_name' is reserved (compose/legacy service name collision)"
  done
  case "$_name" in
    [a-z]*) ;;
    *) die "user name must start with a lowercase letter: '$_name'" ;;
  esac
  _len=${#_name}
  [ "$_len" -le 31 ] || die "user name must be at most 31 characters (got $_len)"
  _rest=${_name#?}
  case "$_rest" in
    *[!a-z0-9_-]*) die "user name may only contain [a-z0-9_-]: '$_name'" ;;
  esac
}

require_password() {
  [ -n "${1-}" ] || die "password must not be empty"
}

# resolve NAME/PASSWORD from DSH_USER_NAME/DSH_USER_PASSWORD (both or neither)
# or fall back to the split positional arguments; $1 = expected arg count.
resolve_name_password() {
  _expected=$1
  if [ -n "${DSH_USER_NAME:-}" ] || [ -n "${DSH_USER_PASSWORD:-}" ]; then
    [ -n "${DSH_USER_NAME:-}" ] && [ -n "${DSH_USER_PASSWORD:-}" ] \
      || die "provide both NAME and PASSWORD, or neither and use: task <task> -- <name> <password>"
    name=$DSH_USER_NAME
    password=$DSH_USER_PASSWORD
  else
    [ "$ARG_COUNT" -eq "$_expected" ] || { usage; exit 2; }
    name=$ARG_1
    password=$ARG_2
  fi
  [ -n "$name" ] || die "user name must not be empty"
}

# ---------------------------------------------------------------------------
# File inspection helpers
# ---------------------------------------------------------------------------
user_in_db() {
  awk -v n="$1" '$0 == "  " n ":" { found = 1 } END { exit !found }' "$USERS_DB"
}

user_has_service() {
  sh "$MODE_HELPER" services | grep -qxF "dsh-$1"
}

user_has_upstream() {
  grep -q "^upstream dsh_$1 " "$GATEWAY_CONF"
}

primary_user() {
  sh "$MODE_HELPER" primary | sed 's/^dsh-//'
}

# ---------------------------------------------------------------------------
# Edit helpers
# ---------------------------------------------------------------------------
# awk_edit <file> [awk args...] — rewrite <file> through a temp copy; on awk
# failure or an empty result the original is left untouched.
awk_edit() {
  _file=$1
  shift
  _tmp="$_file.tmp.$$"
  awk "$@" "$_file" > "$_tmp" || { rm -f "$_tmp"; die "failed to edit $_file"; }
  [ -s "$_tmp" ] || { rm -f "$_tmp"; die "editing $_file produced an empty result; aborted"; }
  mv "$_tmp" "$_file"
}

require_anchor() {
  grep -Eq "$2" "$1" || die "anchor not found in $1: $2 (file format changed?)"
}

# Re-render the gateway template inside the running container and graceful-reload
# nginx (SIGHUP): the master stays up, old workers keep serving established
# SSE/WS connections, new workers use the updated user->backend route table.
# Called after create/remove touch nginx/gateway/default.conf.template so routing changes
# land without recreating the gateway container. Safe even when the target
# dsh-<name> instance is not (yet) running: its upstream server uses `resolve`,
# so nginx -t never fails on a currently unresolvable name (traffic for that
# user just 502s until task dsh:up -- <name> starts the instance).
reload_gateway() {
  if [ "$(docker inspect dsh-base-gateway --format '{{.State.Running}}' 2>/dev/null)" != true ]; then
    echo "note: gateway not running; template changes apply on the next task auth:up"
    return 0
  fi
  if ! docker exec dsh-base-gateway sh -c \
      'NGINX_ENTRYPOINT_QUIET_LOGS=1 /docker-entrypoint.d/20-envsubst-on-templates.sh && nginx -t && nginx -s reload'; then
    die "gateway reload failed; fix nginx/gateway/default.conf.template then retry: task auth:reload"
  fi
  echo "gateway route table reloaded (graceful nginx reload, no restart)"
}

# Start one user's dsh instance (the task dsh:up -- <name> equivalent, mode-aware
# through scripts/compose_mode.sh run — the Taskfile user:create task exports the
# MODE_ENV values this needs) and wait until its inner nginx answers, so the
# gateway reload that follows resolves dsh-<name> immediately and the new user's
# first login cannot hit a 502 from an unstarted/unresolved upstream.
start_instance() {
  _name=$1
  _svc="dsh-$_name"
  echo "starting instance $_svc (container dsh-web-$_name)..."
  if ! sh "$MODE_HELPER" run --profile dsh up -d --no-deps "$_svc"; then
    echo "error: failed to start $_svc (config changes are kept)" >&2
    echo "hint: start it manually with: task dsh:up -- $_name" >&2
    return 0
  fi
  _i=0
  while [ "$_i" -lt 30 ]; do
    if docker exec "dsh-web-$_name" curl -fsS -o /dev/null --max-time 2 \
        http://127.0.0.1:80/ 2>/dev/null; then
      echo "instance dsh-web-$_name is up and serving"
      return 0
    fi
    _i=$((_i + 1))
    sleep 1
  done
  echo "note: dsh-web-$_name still booting after 30s; the very first login may briefly 502" >&2
}

# Syntax-check compose.yaml after structural edits.
compose_check() {
  if ! COMPOSE_PROFILES= docker compose -f "$COMPOSE_FILE" config -q 2>/dev/null; then
    die "compose.yaml failed validation after edit; inspect: docker compose -f compose.yaml config"
  fi
}

# Generate an argon2id digest with the authelia image (output line: "Digest: $argon2...").
generate_hash() {
  COMPOSE_PROFILES= docker compose --profile auth run --rm --no-deps \
    authelia authelia crypto hash generate argon2 --password "$1" 2>/dev/null \
    | sed -n 's/^Digest:[[:space:]]*//p' | sed -n '1p'
}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------
cmd_create() {
  resolve_name_password 2
  validate_name "$name"
  require_password "$password"

  user_in_db "$name" \
    && die "user '$name' already exists in users_database.yml (task user:remove -- $name first)"
  user_has_service "$name" \
    && die "user '$name' already has a dsh-$name service in compose.yaml"
  user_has_upstream "$name" \
    && die "user '$name' already has a gateway upstream"

  # Verify every edit anchor before touching any file
  require_anchor "$COMPOSE_FILE" '^  # -+ dsh runtime image'
  require_anchor "$GATEWAY_CONF" '^upstream dsh_denied '
  require_anchor "$GATEWAY_CONF" '^    default[[:space:]]+dsh_denied;'

  echo "generating argon2id digest for '$name' (authelia image)..."
  hash=$(generate_hash "$password")
  case "$hash" in
    '$argon2'*) ;;
    *) die "authelia did not return an argon2 digest (is docker running?)" ;;
  esac
  domain=${DSH_DOMAIN:-harness.deepseek.com}

  # 1. users_database.yml — append at EOF (the only top-level map is `users:`).
  #    The "dsh" group is what configuration.yml's ACL rule matches; it hot-reloads.
  [ -n "$(tail -c 1 "$USERS_DB")" ] && printf '\n' >> "$USERS_DB"
  {
    printf '  %s:\n' "$name"
    printf '    displayname: %s\n' "$name"
    printf '    password: "%s"\n' "$hash"
    printf '    email: %s@%s\n' "$name" "$domain"
    printf '    groups:\n'
    printf '      - dsh\n'
  } >> "$USERS_DB"

  # 2. compose.yaml — instance block right before the build-only pointer banner
  require_anchor "$COMPOSE_FILE" '^  # -+ dsh runtime image'
  awk_edit "$COMPOSE_FILE" -v name="$name" '
    !done && /^  # -+ dsh runtime image/ {
      print "  # ------------------------------------------------ dsh runtime instance: " name
      print "  dsh-" name ":"
      print "    <<: *dsh-runtime"
      print "    container_name: dsh-web-" name
      print "    volumes:"
      print "      - *dsh-checkout"
      print "      - ./dsh-home/" name ":/data/dsh-home"
      print "      - ./workspace/" name ":/data/workspace"
      print ""
      done = 1
    }
    { print }
  '
  compose_check

  # 3. gateway template — upstream + $dsh_user routing map entry
  require_anchor "$GATEWAY_CONF" '^upstream dsh_denied '
  awk_edit "$GATEWAY_CONF" -v name="$name" '
    !done && /^upstream dsh_denied / {
      print "upstream dsh_" name " { zone dsh_" name " 64k; server dsh-" name ":80 resolve; }"
      done = 1
    }
    { print }
  '
  require_anchor "$GATEWAY_CONF" '^    default[[:space:]]+dsh_denied;'
  awk_edit "$GATEWAY_CONF" -v name="$name" '
    !done && /^    default[[:space:]]+dsh_denied;/ {
      printf "    %-12s dsh_%s;\n", name, name
      done = 1
    }
    { print }
  '

  mkdir -p "$ROOT/dsh-home/$name" "$ROOT/workspace/$name"

  # post-conditions
  user_in_db "$name" || die "post-check failed: $USERS_DB"
  user_has_service "$name" || die "post-check failed: compose.yaml"
  user_has_upstream "$name" || die "post-check failed: gateway/default.conf.template"
  awk -v n="$name" '$0 == "  " n ":" { inblock = 1 }
    inblock && /^    groups:/ { grp = 1 }
    grp && /^      - dsh$/ { ok = 1 }
    END { exit !ok }' "$USERS_DB" \
    || die "post-check failed: $name is missing the dsh group (ACL grants by group:dsh)"

  # Order matters: start the instance FIRST (and wait for it to serve), THEN
  # reload the gateway - nginx resolves dsh-<name> during the reload, so the
  # route becomes usable the moment it appears, with no resolve-cache 502 window.
  start_instance "$name"
  reload_gateway

  echo "user '$name' created and ready (authelia users+groups + dsh-$name + gateway route)."
  echo "zero restart: the users/groups entry hot-reloads via watch: true, the instance is"
  echo "up and the gateway route is live - '$name' can log in right away."
}

cmd_reset() {
  resolve_name_password 2
  require_password "$password"
  user_in_db "$name" || die "user '$name' not found in users_database.yml"

  echo "generating argon2id digest for '$name' (authelia image)..."
  hash=$(generate_hash "$password")
  case "$hash" in
    '$argon2'*) ;;
    *) die "authelia did not return an argon2 digest (is docker running?)" ;;
  esac

  awk_edit "$USERS_DB" -v name="$name" -v hash="$hash" '
    $0 == "  " name ":" { inblock = 1; print; next }
    inblock && /^  [^[:space:]#]/ { inblock = 0 }
    inblock && /^    password:/ { print "    password: \"" hash "\""; next }
    { print }
  '
  # the digest is unique (random salt): its presence proves the replacement
  grep -qF "password: \"$hash\"" "$USERS_DB" || die "password replacement failed for '$name'"

  echo "password for '$name' updated."
  if grep -Eq '^[[:space:]]*watch:[[:space:]]*true' "$AUTH_CONF"; then
    echo "no action needed - authelia hot-reloads the users file (watch: true)"
  else
    echo "apply with: task auth:restart   (authelia must reload the users file)"
  fi
}

cmd_remove() {
  if [ -n "${DSH_USER_NAME:-}" ]; then
    name=$DSH_USER_NAME
  else
    [ "$ARG_COUNT" -eq 1 ] || { usage; exit 2; }
    name=$ARG_1
  fi
  [ -n "$name" ] || die "user name must not be empty"

  user_in_db "$name" || user_has_service "$name" \
    || die "user '$name' does not exist"
  # The primary is simply the first declared dsh service, so removing it is
  # fine while other instances remain: the next service inherits the role.
  # Only the last remaining instance must be kept — AUTH_GATEWAY=false
  # publishes HTTP_PORT on the primary, and it cannot resolve without one.
  _was_primary=
  _primary=$(primary_user)
  if [ "$name" = "$_primary" ]; then
    _count=$(sh "$MODE_HELPER" services | grep -c '')
    [ "$_count" -ge 2 ] || die \
      "cannot remove '$name': it is the last remaining dsh instance" \
      "(the primary service used by AUTH_GATEWAY=false); create another user first"
    _new_primary=$(sh "$MODE_HELPER" services | sed -n '2p' | sed 's/^dsh-//')
    _was_primary=1
    echo "note: '$name' is the primary instance; '$_new_primary' takes over the primary role"
  fi

  # stop the instance first, while compose.yaml still declares the service
  if COMPOSE_PROFILES= docker compose --profile dsh rm -sf "dsh-$name" >/dev/null 2>&1; then
    echo "removed containers of service dsh-$name"
  else
    echo "note: no container removed for dsh-$name (service not running)"
  fi

  # 1. users_database.yml — drop the whole "<name>:" block
  awk_edit "$USERS_DB" -v name="$name" '
    $0 == "  " name ":" { inblock = 1; next }
    inblock && /^  [^[:space:]#]/ { inblock = 0 }
    inblock { next }
    { print }
  '

  # 2. compose.yaml — drop the instance banner + block, collapse blank runs
  _banner_re='^  # -+ dsh runtime instance: '"$name"'$'
  awk_edit "$COMPOSE_FILE" -v banner="$_banner_re" -v svc="  dsh-$name:" '
    !del_banner && $0 ~ banner { del_banner = 1; next }
    !del_block && $0 == svc { del_block = 1; next }
    {
      if (del_block) {
        if ($0 == "" || $0 ~ /^    /) next
        del_block = 0
      }
      if ($0 == "" && prev_blank) next
      prev_blank = ($0 == "")
      print
    }
  '
  compose_check

  # 3. gateway template — drop the upstream and the routing map entry
  _up_re='^upstream dsh_'"$name"' '
  _map_re='^[[:space:]]*'"$name"'[[:space:]]+dsh_'"$name"';[[:space:]]*$'
  awk_edit "$GATEWAY_CONF" -v up="$_up_re" -v map="$_map_re" '
    $0 ~ up || $0 ~ map { next }
    { print }
  '

  # post-conditions
  user_in_db "$name" && die "post-check failed: users_database.yml still contains $name"
  user_has_service "$name" && die "post-check failed: compose.yaml still contains dsh-$name"
  user_has_upstream "$name" && die "post-check failed: gateway/default.conf.template still contains dsh_$name"

  reload_gateway

  echo "user '$name' removed from the users database, compose.yaml and the gateway."
  echo "data preserved: dsh-home/$name and workspace/$name were NOT deleted."
  echo "no action needed: new logins are blocked immediately; authelia refreshes session"
  echo "profiles against the users database (session.refresh_interval, default 5m), so an"
  echo "existing session of '$name' self-invalidates within that window (task auth:restart drops it at once)"
  if [ "$_was_primary" = 1 ]; then
    echo "primary moved to '$_new_primary': also run task up" \
      "(AUTH_GATEWAY=false must republish HTTP_PORT on the new primary)"
  fi
}

cmd_list() {
  _services=$(sh "$MODE_HELPER" services) || die "failed to enumerate dsh services"
  [ -n "$_services" ] || die "no dsh runtime services found in compose.yaml"
  _primary=$(primary_user)
  printf '%-16s %s\n' NAME ROLE
  _count=0
  for _svc in $_services; do
    _name=${_svc#dsh-}
    if [ "$_name" = "$_primary" ]; then
      _role='primary (no-auth single instance)'
    else
      _role='user instance'
    fi
    printf '%-16s %s\n' "$_name" "$_role"
    _count=$((_count + 1))
  done
  printf '%d user(s)\n' "$_count"
}

# ---------------------------------------------------------------------------
main() {
  [ $# -ge 1 ] || { usage; exit 2; }
  command=$1
  split_args
  cd "$ROOT" || exit 2
  case "$command" in
    create) cmd_create ;;
    reset-password) cmd_reset ;;
    remove) cmd_remove ;;
    list) cmd_list ;;
    *)
      usage
      exit 2
      ;;
  esac
}

main "$@"
